using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.DependencyInjection;
using SanitizeService.Api;
using SanitizeService.Api.OpenApi;
using SanitizeService.Application;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((context, services, configuration) =>
{
    configuration.ReadFrom.Configuration(context.Configuration);
});

builder.Services.Configure<SanitizationOptions>(builder.Configuration.GetSection(SanitizationOptions.SectionName));
builder.Services.AddSanitization();

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<SanitizeExceptionHandler>();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
// OpenAPI document is generated by ASP.NET Core (valid top-level "openapi" field). Swagger UI loads it from MapOpenApi.
builder.Services.AddOpenApi(options => OpenApiReferencedSchemaPruner.Register(options));

// Host-wide HTTP body ceiling (independent of per-endpoint file limits; see SanitizationOptions.MaxRequestBodyBytes).
var maxRequestBodyBytes = builder.Configuration.GetValue(
    $"{SanitizationOptions.SectionName}:{nameof(SanitizationOptions.MaxRequestBodyBytes)}",
    SanitizationOptions.DefaultMaxRequestBodyBytes);

builder.Services.Configure<KestrelServerOptions>(o => { o.Limits.MaxRequestBodySize = maxRequestBodyBytes; });
builder.Services.Configure<FormOptions>(o =>
{
    o.MultipartBodyLengthLimit = maxRequestBodyBytes;
});

var app = builder.Build();

var enableOpenApiUi = app.Environment.IsDevelopment()
    || app.Configuration.GetValue("Swagger:Enabled", false);

if (enableOpenApiUi)
{
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/openapi/v1.json", "Sanitize Service v1");
        options.DocumentTitle = "Sanitize Service – Swagger";
    });
}

app.UseExceptionHandler();
app.UseHttpsRedirection();
app.MapControllers();

if (enableOpenApiUi)
{
    app.MapOpenApi();
}

try
{
    app.Run();
}
finally
{
    Log.CloseAndFlush();
}
