using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.DependencyInjection;
using SanitizeService.Api;
using SanitizeService.Application;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((context, services, configuration) =>
{
    configuration.ReadFrom.Configuration(context.Configuration);
});

builder.Services.AddOptions<SanitizationOptions>()
    .Bind(builder.Configuration.GetSection(SanitizationOptions.SectionName))
    .Validate(
        o => o.MaxFileSizeBytes > 0 && o.MaxRequestBodyBytes >= o.MaxFileSizeBytes,
        "Sanitization options are invalid: MaxFileSizeBytes must be > 0 and MaxRequestBodyBytes must be >= MaxFileSizeBytes.")
    .ValidateOnStart();

builder.Services.AddOptions<AbcOptions>()
    .Bind(builder.Configuration.GetSection(AbcOptions.SectionName))
    .Validate(
        o => !string.IsNullOrWhiteSpace(o.HeaderSignature)
            && !string.IsNullOrWhiteSpace(o.FooterSignature)
            && o.BlockSize >= 3
            && o.ValidDigitMin >= 0
            && o.ValidDigitMax <= 9
            && o.ValidDigitMin <= o.ValidDigitMax,
        "ABC options are invalid: Header/Footer are required, BlockSize must be >= 3, and valid digit range must be 0-9.")
    .ValidateOnStart();
builder.Services.AddSanitization();

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<SanitizeExceptionHandler>();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
// OpenAPI document is generated by ASP.NET Core (valid top-level "openapi" field). Swagger UI loads it from MapOpenApi.
builder.Services.AddOpenApi();

// Host-wide HTTP body ceiling (independent of per-endpoint file limits; see SanitizationOptions.MaxRequestBodyBytes).
var maxRequestBodyBytes = builder.Configuration.GetValue(
    $"{SanitizationOptions.SectionName}:{nameof(SanitizationOptions.MaxRequestBodyBytes)}",
    SanitizationOptions.DefaultMaxRequestBodyBytes);

builder.Services.Configure<KestrelServerOptions>(o => { o.Limits.MaxRequestBodySize = maxRequestBodyBytes; });
builder.Services.Configure<FormOptions>(o =>
{
    o.MultipartBodyLengthLimit = maxRequestBodyBytes;
});

var app = builder.Build();

var enableOpenApiUi = app.Environment.IsDevelopment()
    || app.Configuration.GetValue("Swagger:Enabled", false);

if (enableOpenApiUi)
{
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/openapi/v1.json", "Sanitize Service v1");
        options.DocumentTitle = "Sanitize Service – Swagger";
    });
}

app.UseExceptionHandler();
app.UseHttpsRedirection();
app.MapControllers();

if (enableOpenApiUi)
{
    app.MapOpenApi();
}

try
{
    app.Run();
}
finally
{
    Log.CloseAndFlush();
}
